name: marikiti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.1
  flutter_localizations:
    sdk: flutter
  
  google_sign_in: ^6.2.2
  google_sign_in_all_platforms: ^1.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Google.png
    - assets/fruits.jpg
    - assets/dairy.jpg
    - assets/vegetables.jpg
    - assets/vendor1.jpeg
    - assets/vendor2.jpeg
    - assets/vendor3.jpeg
    - assets/mangoes.jpeg
    - assets/coconuts.jpeg
    - assets/potatoes.jpeg
    - assets/fish.jpg
    - assets/banana.png
    - assets/kales.jpeg
    - assets/carrot.jpeg
    - assets/meat.jpeg
    - assets/avocado.jpeg
    - assets/milk.jpeg
    - .env  

      