// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR6452wBKkSza5lPKBy0NM8zEURlrAqZ8',
    appId: '1:197018124250:web:21a7ab1f915265ab288ae3',
    messagingSenderId: '197018124250',
    projectId: 'freshmarikti',
    authDomain: 'freshmarikti.firebaseapp.com',
    storageBucket: 'freshmarikti.firebasestorage.app',
    measurementId: 'G-8YW4DS8MY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlRFkBMEpCbGqVe5UBbxSF_jZyewRzB9E',
    appId: '1:197018124250:android:503f0890d0fe5cb6288ae3',
    messagingSenderId: '197018124250',
    projectId: 'freshmarikti',
    storageBucket: 'freshmarikti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4AyB3jMJvwE2z92kyzvWSWRWvM5wiGpg',
    appId: '1:197018124250:ios:8c14baf255c92aae288ae3',
    messagingSenderId: '197018124250',
    projectId: 'freshmarikti',
    storageBucket: 'freshmarikti.firebasestorage.app',
    iosBundleId: 'com.example.marikiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4AyB3jMJvwE2z92kyzvWSWRWvM5wiGpg',
    appId: '1:197018124250:ios:8c14baf255c92aae288ae3',
    messagingSenderId: '197018124250',
    projectId: 'freshmarikti',
    storageBucket: 'freshmarikti.firebasestorage.app',
    iosBundleId: 'com.example.marikiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR6452wBKkSza5lPKBy0NM8zEURlrAqZ8',
    appId: '1:197018124250:web:a97f2d50991163aa288ae3',
    messagingSenderId: '197018124250',
    projectId: 'freshmarikti',
    authDomain: 'freshmarikti.firebaseapp.com',
    storageBucket: 'freshmarikti.firebasestorage.app',
    measurementId: 'G-0P0MGXZ919',
  );
}
