name: fresh_marikiti
description: A fresh food delivery app with eco-friendly focus

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  # Google Maps and Location Tracking
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  # UI Components
  flutter_svg: ^2.0.9
  # Utilities
  intl: ^0.17.0
  sqflite: ^2.3.0
  # Phase 4: Payment & Advanced Features
  # Charts and visualization
  fl_chart: ^0.66.0
  
  # HTTP and API improvements
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # File handling and uploads
  file_picker: ^8.0.0+1
  path: ^1.8.3
  
  # Crypto and security for payment processing
  crypto: ^3.0.3
  convert: ^3.1.1
  
  # Additional UI components
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  
  # Device and system info
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
