// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpdCoEe_tVpjnhu0J-kwKZMWohet57eL4',
    appId: '1:508208214291:web:48ccca49a1d36dc79f2ae6',
    messagingSenderId: '508208214291',
    projectId: 'fresh-marikiti',
    authDomain: 'fresh-marikiti.firebaseapp.com',
    storageBucket: 'fresh-marikiti.firebasestorage.app',
    measurementId: 'G-VWXWC8239Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZzRk9uBUcAwOlRTaBjtuo5mkDTrZRxUk',
    appId: '1:508208214291:android:951c83595d47fd609f2ae6',
    messagingSenderId: '508208214291',
    projectId: 'fresh-marikiti',
    storageBucket: 'fresh-marikiti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ZtD-j4H7xg70bvN2TsDrZYRssCd9FYw',
    appId: '1:508208214291:ios:8922694e5d53fadb9f2ae6',
    messagingSenderId: '508208214291',
    projectId: 'fresh-marikiti',
    storageBucket: 'fresh-marikiti.firebasestorage.app',
    iosBundleId: 'com.example.freshMarikiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ZtD-j4H7xg70bvN2TsDrZYRssCd9FYw',
    appId: '1:508208214291:ios:8922694e5d53fadb9f2ae6',
    messagingSenderId: '508208214291',
    projectId: 'fresh-marikiti',
    storageBucket: 'fresh-marikiti.firebasestorage.app',
    iosBundleId: 'com.example.freshMarikiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpdCoEe_tVpjnhu0J-kwKZMWohet57eL4',
    appId: '1:508208214291:web:b2faf67ff388a0339f2ae6',
    messagingSenderId: '508208214291',
    projectId: 'fresh-marikiti',
    authDomain: 'fresh-marikiti.firebaseapp.com',
    storageBucket: 'fresh-marikiti.firebasestorage.app',
    measurementId: 'G-ZZ3QTS0FJS',
  );
}
